services:
  landingpage:
    image: krasosu-landingpage:latest
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landingpage.rule=Host(`krasosu.de`) || Host(`www.krasosu.de`)"
      - "traefik.http.routers.landingpage.entrypoints=https"
      - "traefik.http.routers.landingpage.tls.certresolver=http"
      - "traefik.http.routers.landingpage.middlewares=default@file"
      - "traefik.http.services.landingpage.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
